# Generated by Django 4.0.4 on 2022-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_exam_solution_alter_result_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
