# Generated by Django 4.0.4 on 2022-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_problem_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='pending',
        ),
        migrations.AlterField(
            model_name='problem',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
